[package]
name = "plafond"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
nix = { version = "0.30.1", features = ["user"] }
procfs = "0.17.0"
sysinfo = "0.36.1"
anyhow = "1.0.98"